services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ":8080"
    networks:
        - shared-network

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - shared-network

  nginx:
    image: nginx:1.21.0-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    networks:
      - shared-network
networks:
  shared-network:
    driver: bridge