name: Java CI with Maven

on:
  push:
    branches: [ "deployement" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: running tests
      run: mvn test -Dnet.bytebuddy.experimental=true

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
    - uses: actions/checkout@v3
    
    - name: Cleanup old files on VM
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          rm -rf ~/app/*
          
    - name: Copy deployment files to VM
      uses: appleboy/scp-action@master
      with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{secrets.EC2_SSH_PRIVATE_KEY}}
          source: "./"
          target: "~/app"
          strip_components: 1
          debug: true 
          
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd ~/app
            docker-compose up -d --build
